SELECT [AddressID]
      ,CASE when [BuildingName] like '' then 'no building name' when [BuildingName] is NULL then 'no building name' ELSE 'building name' END as [BuildingName]
      ,CASE when [Line1] not like 'Not Yet Provided' then 'line1' ELSE 'no line1' END as [Line1]
      ,CASE when [Line2] not like '' then 'line2' ELSE 'no line2' END as [Line2]
      ,CASE when [Line3] not like '' then 'line3' ELSE 'no line3' END as [Line3]
      ,CASE when [City] not like 'Not Yet Provided' then 'city' ELSE 'no city' END as [City]
      ,CASE when [County] not like '' then 'county' ELSE 'no county' END AS [County]
      ,[Postcode]
      ,CASE when LEN(REPLACE([Telephone], ' ', '')) = 11 or LEN(REPLACE([Telephone], ' ', '')) = 10 then 1 else 0 end as [Telephone]
      ,CASE when [Fax] like '' then 0 when [Fax] is NULL then 0 ELSE 1 END AS [Fax]
      ,SUBSTRING([Email], CHARINDEX('@', [Email], 1) + 1, 100) as [Email]
      ,[ConcurrencyID]
      ,[CreateDate]
      ,[EndDate]
      ,[BHTA]
      ,CASE when LEN(REPLACE([Mobile], ' ', '')) = 11 or LEN(REPLACE([Mobile], ' ', '')) = 10 then 1 else 0 end as [Mobile]
      ,[ModifiedDate]
      ,[ModifiedByUserID]
FROM [{database}].[dbo].[{table_name}]
where {date_col} between '{last_date}' and '{now_date}'