SELECT [UserID]
      ,[SystemID]
      ,[LocalID]
      ,[Title]
      ,'removed' as [FirstName]
      ,'removed' as [MiddleName]
      ,'removed' as [LastName]
      ,'removed' as [UserName]
      ,[Pwd]
      ,[CreateDate]
      ,[EndDate]
      ,CASE when LEN(REPLACE([Telephone], ' ', '')) = 11 or LEN(REPLACE([Telephone], ' ', '')) = 10 then 1 else 0 end as [Telephone]
      ,CASE when LEN(REPLACE([Mobile], ' ', '')) = 11 or LEN(REPLACE([Mobile], ' ', '')) = 10 then 1 else 0 end as [Mobile]
      ,[SPTypeID]
      ,[UserRole]
      ,SUBSTRING([Email], CHARINDEX('@', [Email], 1) + 1, 100) as [Email]
      ,[PhotoID]
      ,[ConcurrencyID]
      ,[TsnCsConfirm]
      ,[TsnCsType]
      ,[SkipMPQ]
      ,[Ethnicity]
      ,[DOB]
      ,[Sex]
      ,[Source]
      ,[TsnDPConfirm]
      ,[ModifiedDate]
      ,[ModifiedByUserID]
      ,[Id]
      ,[AgreeTerms]
      ,[AgreePrivacy]
      ,[AgreeResearch]
FROM [{database}].[dbo].[{table_name}]
where {date_col} > '{last_date}'