SELECT [Id]
      ,'removed' as [Username]
      ,SUBSTRING([Email], CHARINDEX('@', [Email], 1) + 1, 100) as [Email]
      ,[SumOfTasks]
      ,CASE when LEN(REPLACE([Mobile], ' ', '')) = 11 or LEN(REPLACE([Mobile], ' ', '')) = 10 then 1 else 0 end as [Mobile]
      ,'removed' as [FirstName]
      ,'removed' as [LastName]
      ,CASE when [Address] is not NULL then 'address' ELSE 'no address' END AS [Address]
      ,[DoB]
      ,CASE when [FacebookId] is not NULL then 'fb id' ELSE 'no fb id' END AS [FacebookId]
      ,[Ethnicity]
      ,[Gender]
      ,CASE when [AddressFirstLine] is not NULL then 'line1' ELSE 'no line1' END AS [AddressFirstLine]
      ,CASE when [AddressSecondLine] is not NULL then 'line2' ELSE 'no line2' END AS [AddressSecondLine]
      ,CASE when [City] is not NULL then 'city' ELSE 'no city' END AS [City]
      ,[Postcode]
      ,[CreateDate]
      ,[ModifiedDate]
      ,[EndDate]
FROM [{database}].[dbo].[{table_name}]
where {date_col} > '{last_date}'